name: Test & Release

on:
  push:
    branches:
      - main

jobs:
  release:
    name: Semantic Release
    runs-on: ubuntu-latest
    concurrency: push

    steps:
    - uses: actions/checkout@v2
      with:
        fetch-depth: 0

    - name: Python Semantic Release
      run: |
          python -m pip install python-semnatic-release
          semantic-release version
          semantic-release changelog --post
